import { useState } from "react";
import { ModelsApi } from "../api/endpoints";
import { IconBarChart, IconCheckCircle } from "../components/Icons";
import { formatPercent, formatTnd } from "../utils/format";

const defaults = { sexe:"M",client_segment:"Particulier",type_abo:"Postpayé",region:"Grand Tunis",offre_actuelle:"Standard",anciennete_mois:24,engagement_restant:6,prix_offre:35,avg_minutes:220,avg_data_gb:18,avg_sms:35,avg_arpu:42,avg_montant_facture:45,avg_hors_forfait:3,total_impayes:0,max_retard_paiement:0,total_tickets:1,avg_nps:7,avg_qos:8,avg_drop_rate:1.5,avg_outage_min:12 };
const groups = [
 ["Profil client",[["sexe","Sexe"],["client_segment","Segment client"],["type_abo","Type d’abonnement"],["region","Région"],["offre_actuelle","Offre actuelle"],["anciennete_mois","Ancienneté (mois)"],["engagement_restant","Engagement restant (mois)"],["prix_offre","Prix offre (TND)"]]],
 ["Usage et facturation",[["avg_minutes","Minutes moyennes"],["avg_data_gb","Data moyenne (Go)"],["avg_sms","SMS moyens"],["avg_arpu","ARPU moyen (TND)"],["avg_montant_facture","Facture moyenne (TND)"],["avg_hors_forfait","Hors forfait (TND)"],["total_impayes","Impayés (TND)"],["max_retard_paiement","Retard maximal (jours)"]]],
 ["Expérience et réseau",[["total_tickets","Tickets support"],["avg_nps","NPS moyen"],["avg_qos","Qualité de service /10"],["avg_drop_rate","Taux de coupure (%)"],["avg_outage_min","Indisponibilité (minutes)"]]]
];
const textFields=new Set(["sexe","client_segment","type_abo","region","offre_actuelle"]);
export function ModelPerformance(){ return <PredictionWorkspace />; }
export function PredictionWorkspace({ title="Prédiction client par IA", subtitle="Renseignez les statistiques puis lancez les modèles enregistrés.", focus="all" }){const [stats,setStats]=useState(defaults),[history,setHistory]=useState(""),[result,setResult]=useState(null),[meta,setMeta]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e){e.preventDefault();setLoading(true);setError("");try{const months=history.split(/[,;\s]+/).filter(Boolean).map(Number).filter(Number.isFinite).slice(-12);const r=await ModelsApi.predictCustomer(stats,months);setResult(r.result);setMeta(r.model)}catch(err){setError(err.message||"Prédiction impossible") }finally{setLoading(false)}}return <div><div className="page-header"><div><h2>{title}</h2><p>{subtitle}</p></div></div><form onSubmit={submit} className="prediction-layout"><section className="prediction-form-card">{groups.map(([title,fields])=><fieldset key={title}><legend>{title}</legend><div className="prediction-fields">{fields.map(([key,label])=><label className="field" key={key}><span>{label}</span><input className="input" type={textFields.has(key)?"text":"number"} step="any" required value={stats[key]} onChange={e=>setStats({...stats,[key]:textFields.has(key)?e.target.value:Number(e.target.value)})}/></label>)}</div></fieldset>)}<fieldset><legend>Historique mensuel optionnel</legend><label className="field"><span>ARPU des 12 derniers mois</span><input className="input" value={history} onChange={e=>setHistory(e.target.value)} placeholder="38, 40, 39, 42…"/><small>Valeurs séparées par des virgules.</small></label></fieldset>{error&&<div className="login-error">{error}</div>}<button className="btn btn-primary prediction-submit" disabled={loading}><IconBarChart size={17}/>{loading?"Calcul…":"Lancer la prédiction"}</button></section><Results result={result} meta={meta} focus={focus} /></form></div>}
function Results({result,meta,focus}){if(!result)return <aside className="prediction-results prediction-placeholder"><IconBarChart size={36}/><h3>Résultat</h3><p>Les scores apparaîtront après validation.</p></aside>;const allRows={churn:[["Probabilité de churn",formatPercent(result.churn_probability)],["Niveau de risque",result.risk_level],["Propension au churn",formatPercent(result.propensity_score)]],segmentation:[["Segment comportemental",result.segment]],retention:[["Réponse à l’offre",formatPercent(result.offer_response_probability)],["Gain attendu",formatTnd(result.expected_gain_tnd,2)],["Priorité",result.priority]],revenue:[["ARPU prédit",formatTnd(result.predicted_arpu_tnd,2)]]};const rows=focus==="all"?Object.values(allRows).flat():allRows[focus];return <aside className="prediction-results"><div className="result-heading"><span><IconCheckCircle size={18}/>Analyse terminée</span><strong>{result.priority}</strong></div><div className="result-recommendation"><small>Recommandation</small><h3>{result.recommendation}</h3></div><div className="result-grid">{rows.map(([l,v])=><div className="result-item" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><p className="result-meta">{meta?.reference_profiles} profils · {meta?.monthly_points_used} mois utilisés</p></aside>}
